language: node_js

os: linux

dist: xenial

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - 12

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - Diegoalesco95@hotmail.com
    on_success: always
    on_failure: always

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: src/server/public
  target_branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: master
