language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn dll
  - yarn build

notifications:
  email:
    recipients:
      - Diegoalesco95@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: Platzi-video/dist/
  target_branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: master
