language: node_js

git:
  depth: 3

branches:
  only:
  - master
  - stable

script:
  - yarm build

notification:
  recipients:
    - Diegoalesco95@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: master